Update s3bucketcreation_Jenkinsfile

diff --git a/s3bucketcreation_Jenkinsfile b/s3bucketcreation_Jenkinsfile
--- a/s3bucketcreation_Jenkinsfile
+++ b/s3bucketcreation_Jenkinsfile
@@ -24,10 +24,10 @@ pipeline {
                     secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                 ]]) {
                     sh '''
-                        echo "Creating S3 bucket: koteshbucket-767397794296 in region: us-east-1"
-                        aws s3api create-bucket --bucket koteshbucket-767397794296 --region us-east-1 --create-bucket-configuration LocationConstraint=ap-southeast-1 || echo "Bucket may already exist"
+                        echo "Creating S3 bucket: koteshbucket-767397794296123 in region: us-east-1"
+                        aws s3api create-bucket --bucket koteshbucket-767397794296123 --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1 || echo "Bucket may already exist"
                         echo "Verifying bucket..."
-                        aws s3 ls | grep awsdemojenkins6745ght1 || echo "Bucket not found"
+                        aws s3 ls | grep koteshbucket-767397794296123 || echo "Bucket not found"
                     '''
                 }
             }
